### ISSUE TITLE
Download of Image Files not working on all Browsers as expected

### ISSUE THREAD

**Issue by mlechner** [HsKA-OSGIS/OSTaps#1]
Hi,

try this js-library to add browser-specific support for Download of generated img-Objects (Images, ...):
http://danml.com/download.html

Best regards
Marco Lechner

**Comment by mlechner** [comment]
see https://github.com/OpenBfS/gis-client/blob/d8f4ec93b8c8216b6bdc927e07c742d61151f726/src/app/view/window/BarChartController.js as an usage example.

**Comment by lukasalexanderweber** [comment]
Closed with
https://github.com/HsKA-OSGIS/OSTaps/commit/550009c8056f141bf1c60c70555320d6f32d2c5f
